apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: site
spec:
  volumes:
    - name: nginx-conf
      configMap:
        name: file-nginx
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
    envFrom:
      - configMapRef:
          name: env-nginx
    volumeMounts:
      - mountPath: /etc/nginx/templates/
        name: nginx-conf
    # env:
    #   - name: NGINX_PORT
    #     value: "8000"
